"""update_the_table

Revision ID: a9842d41bf6b
Revises: 
Create Date: 2026-05-14 22:27:20.402014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9842d41bf6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('SeniorCitizen', sa.Integer(), nullable=False),
    sa.Column('Partner', sa.String(), nullable=False),
    sa.Column('Dependents', sa.String(), nullable=False),
    sa.Column('tenure', sa.Integer(), nullable=False),
    sa.Column('PhoneService', sa.String(), nullable=False),
    sa.Column('MultipleLines', sa.String(), nullable=False),
    sa.Column('InternetService', sa.String(), nullable=False),
    sa.Column('OnlineSecurity', sa.String(), nullable=False),
    sa.Column('OnlineBackup', sa.String(), nullable=False),
    sa.Column('DeviceProtection', sa.String(), nullable=False),
    sa.Column('TechSupport', sa.String(), nullable=False),
    sa.Column('StreamingTV', sa.String(), nullable=False),
    sa.Column('StreamingMovies', sa.String(), nullable=False),
    sa.Column('Contract', sa.String(), nullable=False),
    sa.Column('PaperlessBilling', sa.String(), nullable=False),
    sa.Column('PaymentMethod', sa.String(), nullable=False),
    sa.Column('MonthlyCharges', sa.Float(), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    # ### end Alembic commands ###
